### ISSUE TITLE
Open source version slow on purpose?

### ISSUE THREAD

**Issue by jeveloper** [OpenHFT/Chronicle-Engine#9]
Hi 

Your chart is interesting, normally enterprise means extra features, etc, however performance should be the same, how is it that its 10 times slower.
Hazelcast and others offer the same framework and charge for support and enterprise specific features... same with gridgain
thanks

**Comment by peter-lawrey** [comment]
Paying clients often have specific actions they need to be fast. We can
optimise and test those actions to ensure they deliver the performance they
need.
However we don't have performance tests for every possible combination of
setting and action so if you want support for free we don't look to achieve
as agreesive performance targets, we only try to be faster than our
competition.
The numbers are the treshold at which we consider it a bug. The actual
performance is likely to be different and these numbers most likely need
revision as we have made significant improvements since then.

Regards, Peter.

**Comment by peter-lawrey** [comment]
We don't slow down the open source very but we don't claim that for
anything you need it to do we will fix the performance for you as much as
if you pay for support.

**Comment by jeveloper** [comment]
Thank you for quick response Peter

However it does state in readme:
Chronicle Enterprise will be tested to a higher spec and will have more **heavily optimized** components.

So that still means oss version is slower on purpose. 
From what i understand, if someone contributes to Gridgain or hazelcast or others, that benefits them as much as they contribute to oss or community version and making one substantially slower isn't a good OSS practice (unless you're oracle).

cheers

**Comment by peter-lawrey** [comment]
I guess I don't understand how you come to that conclusion.  Like I said
the code is the same.
The performance is the same for an given operation, the only difference is
what a developer can expect us to fix depending on whether they pay for it
or not. However, once fixed, that improvement is available to everyone.

**Comment by peter-lawrey** [comment]
We don't have an OSS version and a commercial version of the code.

**Comment by jeveloper** [comment]
Ahhh, ok i was a bit confused by that point on readme.
Thanks for confirming that it is the same. It just seemed like oss isnt optimized but enterprise is.

**Comment by peter-lawrey** [comment]
That is good feedback. I will update the documentation to make this clearer.
